### ISSUE TITLE
Temperature control issue

### ISSUE THREAD

**Issue by geemodo** [mining-visualizer/MVis-tokenminer#2]
My computer with 2xRX 580 were crashing (being shutdown) after running for about half an hour. Tried increasing the *TEMP* under [ThermalProtection] and it still happened. Then finally today commented out the complete [ThermalProtection] section and have been running for almost a day now, no shutdowns. Temperature of the cards are stable (75, 74). Using Radeon 18.2.1 version of driver.

**Comment by mining-visualizer** [comment]
I guess by TEMP you mean the ThrottleTemp setting, which is  set to 80 in the .ini as shipped.  So that means if your rig was shutting down due to thermal runaway,  your gpus were exceeding 80C!!  I would say it was a good thing the miner shut down. :)  I'm surprised that you then INCREASED the setting!  

Commenting out the settings puts  the ThrottleTemp value back to its default of 80.

**Comment by geemodo** [comment]
Yes the temps now are 74 and 74 on both the cards. has been running for almost 24 hours without any issues
